Webinator/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: "user/sessions", registration: "user/registrations" }

  root 'profiles#index'

  resources :users do
		resources :groups do
      resources :subscriptions, only: [:create]
    end
    resources :profiles
    resources :walls, only: [:show] do
      resources :posts, only: [:create, :show] do
        resources :comments, only: [:create, :index]
      end
    end
    resources :friendships, only: [:create, :destroy]
    resources :feed_histories, only: [:show]
  end

  resources :groups, only: [:show, :destroy]
  resources :tags, only: [:index]

  patch 'friendships/read_requests' => 'friendships#read_requests'
  patch 'friendships/accept_friendship/:id' => 'friendships#accept_friendship'
  patch 'friendships/decline_friendship/:id' => 'friendships#decline_friendship'
  patch 'notifications/read_notifications/' => 'notifications#read_notifications'
  post  'posts/like' => 'posts#like'
  post  'comments/like' => 'comments#like'
  get 'comments/check_for_like' => 'comments#check_for_like'
  get 'users/:user_id/feed_histories/:id/sort_by_date' => 'feed_histories#sort_by_date'
  get 'users/:user_id/feed_histories/:id/sort_by_recommended' => 'feed_histories#sort_by_recommended'
  delete 'users/:user_id/groups/:group_id/subscriptions' => 'subscriptions#delete', as: :destroy_subscription

end

Webinator/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  mount_uploader :avatar, AvatarUploader
  validates :first_name, presence: true
  validates :last_name, presence: true
end

Webinator/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  helper ApplicationHelper

  def index
    @profile = current_user.profile
    if @profile.blank?
      redirect_to new_user_profile_path(current_user.id)
    end

    if !current_user.profile.nil?
      redirect_to user_profile_path(current_user.id, current_user.profile.id)
    end
  end

  def new

		@tags = Tag.all
		
    if current_user.id == params[:user_id]
      @profile = Profile.new
      flash[:notice] = "K"
    else
      flash[:error] = "You shouldn't be here!"
    end
  end

  def show
    if current_user.profile.blank?
      redirect_to new_user_profile_path(current_user.id)
    end



    if params[:id].blank?
      params[:user_id] = current_user.id
      params[:id] = current_user.profile.id
    end

    @profile = Profile.find(params[:id])
    @friendship = Friendship.where(:user_id => current_user.id, :friend_id => params[:user_id].to_i).first
    if @friendship.blank?
      @friendship = Friendship.where(:user_id => params[:user_id].to_i, :friend_id => current_user.id).first
    end

  end

  def edit
    byebug
    @profile = Profile.find(params[:id])

    redirect_to :back
  end

def update
    @profile = Profile.find(params[:id])
    @profile.first_name = params[:profile][:first_name]
    @profile.last_name = params[:profile][:last_name]
    @profile.avatar = params[:profile][:avatar]
    @profile.birthday = params[:profile][:birthday]
    @profile.save

    flash[:notice] = "User profile succesfully updated!"
    redirect_to user_profile_path(current_user.id, current_user.profile.id)
end

  def create
		
		@res = {
			:msg => 'Unknown Error'
			}
		
    @profile = Profile.new
    @profile.first_name = params[:first_name]
    @profile.last_name = params[:last_name]
    @profile.user_id = current_user.id
		
		@cats = params[:categories]
		@user = User.find(current_user.id)
		
		@cats.each do |cat| 
      @user.tags << Tag.find(cat[:id])
    end
		
		

    if @profile.save
      @user.wall = Wall.create()
      @feed = Feed.create(:user_id => current_user.id)
      FeedHistory.create(:feed_id => @feed.id)
			
			@res = {
				:redirect_url => user_profiles_path(current_user.id).to_s
				}
		end

    # Profile.create(:first_name => params[:profile][:first_name], :last_name => params[:profile][:last_name],
    #                :user_id => current_user.id, :avatar => "/images/default-avatar.png")
		
		render :json => { :redirect_url => user_profiles_path(current_user.id).to_s	}
  end
end

Webinator/app/helpers/profile_helper.rb
module ProfileHelper
end

Webinator/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Webinator/app/views/profiles/edit.html.erb
<h2> edit yer freakin profile </h2>

<%= form_for [current_user, @profile] do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.file_field :avatar %>
  <%= f.submit "Update" %>
<% end %>

Webinator/app/views/profiles/index.html.erb
<h2> Yer freakin profile! </h2>

<ul>
	<li> First name: <%= @profile.first_name %></li>
	<li> First name: <%= @profile.last_name %></li>
</ul>

Webinator/app/views/profiles/new.html.haml
.container-fluid
	.row.feed_title
		.col-md-3
		.col-md-6
			%h2 Profile Information
		.col-md-3
%br
	.row
		.col-md-3
		.col-md-6
			.panel.panel-default
				.panel-body
					= react_component('ProfileCreateView', {user_id: params[:user_id]})
		.col-md-3

Webinator/app/views/profiles/show.html.haml
.container-fluid
  .row.feed_title
    .col-md-4
    .col-md-4.profile_title
      - if current_user.id == params[:user_id].to_i
        %h2 Your Profile
      - elsif
        %h2= @profile.last_name + "'s Profile"
    .col-md-4
  %br
  .row
    .col-md-4
    .col-md-4
      .row
        .col-md-4
          .thumbnail
            %img{:src => @profile.avatar}
        .col-md-8
          %ul.list-group
            %li.list-group-item
              %label First name:
              = @profile.first_name
            %li.list-group-item
              %label Last name:
              = @profile.last_name
            %li.list-group-item
              %label Birthday:
              = @profile.birthday
            %br
            %br
            .row
              .col-md-4
              .col-md-4
                - if current_user.id == params[:user_id].to_i
                  .btn.btn-default{"data-toggle" => "collapse", "data-target" => "#collapsable"} Edit Your Profile
                - elsif @friendship.blank?
                  = link_to "Add Friend",  user_friendships_path(:user_id => current_user.id, :friend_id => params[:user_id]), :method => :post, :class => "btn btn-primary"
                - elsif @friendship.accepted?
                  = link_to "Unfriend", user_friendship_path(current_user.id, @friendship.id), :method => :delete, :class => "btn btn-default"
                - else
                  = link_to "Accept Friend", { controller: 'friendships', action: 'accept_friendship', id: @friendship.id }, :method => :patch, :class => "btn btn-primary"
              .col-md-4
      .row.collapse{:id => "collapsable"}
        .col-md-12
          .panel
            .panel-body
              = form_for [current_user, @profile], method: :patch do |f|
                = f.label :first_name
                %br
                = f.text_field :first_name, class: "form-control"
                %br
                = f.label :last_name
                %br
                = f.text_field :last_name, class: "form-control"
                %br
                %label Upload Image:
                %br
                = f.file_field :avatar
                %br
                = f.label :birthday
                %br
                = f.date_field :birthday
                %br
                = f.submit "Update", class: "btn btn-primary"

    .col-md-4

Webinator/app/views/profiles/update.html.erb
<h1> User profile updated  </h2>